name: exe5
on:
    workflow_dispatch:
    schedule:
       # - cron: '*/2 * * * *'
jobs:
    learning:
        runs-on: ubuntu-latest
        steps:
            - name: corn-job 
              run: "echo hwllo"
              
